package com.ericsson.sscm.esb.rules;


import com.ericsson.sscm.esb.model.data.Attribute;
import com.ericsson.sscm.esb.model.data.Request;
import com.ericsson.sscm.esb.model.data.StatusValue;
import com.ericsson.sscm.esb.constants.AirInternalConstants;

import com.ericsson.sscm.esb.model.data.AbstractInOut;
import com.ericsson.sscm.esb.constants.CommonConstants;
import com.ericsson.sscm.esb.model.data.Response;
import com.ericsson.sscm.esb.model.data.NodeResponse;
import com.ericsson.sscm.esb.model.data.Criteria;
import com.ericsson.sscm.esb.model.data.FulfillmentState;

import java.util.Date;
import java.util.Calendar;
import java.util.Properties;

global org.slf4j.Logger logger;

rule "post_CustomKorekTestOutboundService"
	when
        $request : Request( nextNodeIdentifier == "CustomKorekTestOutboundService",
                            flowName == "fulfillService",
                            isLastOperation("setSubscriberData") == true )
    then
        Object desc = $request.getLastResponse().getNodeResponse().get("description");
        logger.debug("CustomKorekTestOutboundService.setSubscriberData entered. desc: " +desc);
        if (desc != null) {
            Attribute attribute = new Attribute("KOREK_TEST", desc);
            $request.getNodeRequest().addAttribute(attribute);
        }
        $request.getLastResponse().getNodeResponse().setStatus(StatusValue.SUCCESS);
        $request.getNodeRequest().add("STATE_CHANGED",true);
        Object origMess = $request.getLastResponse().getNodeResponse().get("originalMessage");
        logger.debug("CustomKorekTestOutboundService.setSubscriberData entered. origMess: " + origMess);
end

