package com.ericsson.sscm.esb.rules;

import com.ericsson.sscm.esb.model.data.Request;
import com.ericsson.sscm.esb.model.data.Attribute;
import com.ericsson.sscm.esb.model.data.AbstractInOut;
import com.ericsson.sscm.esb.constants.CommonConstants;
import com.ericsson.sscm.esb.model.data.StatusValue;

import com.ericsson.sscm.esb.model.data.Response;
import com.ericsson.sscm.esb.model.data.NodeResponse;
import com.ericsson.sscm.esb.model.data.Criteria;

global org.slf4j.Logger logger;

import function com.ericsson.sscm.esb.rules.beans.PropertyReader.getProperty;

rule "fulfillService_CustomKorekTestOutboundService"
    when
        $request : Request( flowName == "fulfillService", $profile:nodeRequest.get("serviceprofile").toString())
        Request( getProperty($profile).equals("CustomKorekTestOutboundService") == true)
        Request( $request.isVisited ("CustomKorekTestOutboundService", "setSubscriberData") == false)
        Request( $request.getNodeRequest().getAttributeStartsWithName("PARAM_1").isEmpty() == false)
    then
        $request.setNextOperation("setSubscriberData");
		logger.debug("nextOperation:setSubscriberData");
end
